language: node_js
node_js:
  - "node"

cache:
  directories:
  - node_modules
  - $HOME/.meteor/

before_install:
  - curl https://install.meteor.com | /bin/sh

after_success:
  - .travis/push.sh

sudo: required